feat: Add stats and support for mocking
allmygames/GOGDotNet pull request #3
Opened 2021-10-03 01:47 UTC by kamranayub

Thanks @MChartier, this has been working great. The only thing I needed was the extra `stats` info and since I am writing tests against GOG, I needed to be able to mock `GetGameStatsAsync` so if it's OK, I marked it `virtual` so the mocking framework can overwrite it (otherwise, it could have an interface and that'll work too).

## Changes

- Added stats fields:
  - `AchievementsPercentage`
  - `Playtime` (in hours, I think?)
  - `LastSession`
- Tests for the game data coming back
- Marked `GetGameStatsAsync` as `virtual` for mocking

2021-10-03 04:20 UTC, MChartier requested changes
Looks good overall, thanks for submitting this pull request!

Please address the minor stylistic comments, and I'll be happy to approve the next iteration.

2021-10-03 04:20 UTC, MChartier commented on GOGDotNet/GOGClient.cs
> +
Nit: Remove extra line breaks.

2021-10-03 04:20 UTC, MChartier commented on GOGDotNet/GOGClient.cs
> +                        // stats: { "<id>": object }
Please remove these commented lines before checking in.

2021-10-03 08:09 UTC, MChartier commented
Oh one more thing, please bump the version number in `GOGDotNet.csproj` to update the version number from 0.1.1 to 0.2.0.

(Updating minor version because you've added new functionality without breaking an existing interface.)

This is important because otherwise this change won't trigger a new version of the package to be published to NuGet, and you won't be able to consume it from there.

2021-10-03 18:26 UTC, kamranayub commented on GOGDotNet/GOGClient.cs
> +
```suggestion
```

2021-10-03 18:26 UTC, kamranayub commented on GOGDotNet/GOGClient.cs
> +                        // stats: { "<id>": object }
```suggestion
```

2021-10-03 19:13 UTC, MChartier commented
> 
> 
> Oh one more thing, please bump the version number in `GOGDotNet.csproj` to update the version number from 0.1.1 to 0.2.0.
> 
> (Updating minor version because you've added new functionality without breaking an existing interface.)
> 
> This is important because otherwise this change won't trigger a new version of the package to be published to NuGet, and you won't be able to consume it from there.

The version number still hasn't been updated, just mentioning in case you intended to include in your updated commit. Once you fix that I'll be happy to accept and merge!

2021-10-05 13:42 UTC, kamranayub commented
Should be good now!

2021-10-06 05:17 UTC, MChartier approved these changes

2021-10-06 05:17 UTC, merged